Mysql:
  host: "localhost"
  port: "3306"
  user: "用户名"
  password: "数据库密码"
  charset: "utf8"
  database: "TeamToDo"
Redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
RSA:
  PublicKey: ""
  PrivateKey: ""
COS:
  url: "https://<桶名>.cos.<地域>.myqcloud.com"
  SecretID: "ID"
  SecretKey: "Key"
DefaultAvatar:
  userUrl: "默认用户头像链接"
  groupUrl: "默认群组头像链接"
"JWT":
  "SecretKey": "key"
  "ExpireTime": 36000
"mail":
  "Username": "邮箱地址（网易）"
  "Secret": "授权码"
  "Host": "smtp.163.com"
  "Port": 25




